# Generated by Django 4.2.3 on 2023-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='time',
            field=models.TimeField(),
        ),
    ]
