# Generated by Django 4.2.3 on 2023-08-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0002_alter_today_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='today',
            name='time',
        ),
    ]
